postgresql:
  enabled: false

database:
  type: postgresql
  driver: org.postgresql.Driver
  secrets:
    user:
      name: jfrog-secret
      key: db-user
    password:
      name: jfrog-secret
      key: db-password
    url:
      name: jfrog-secret
      key: db-url

artifactory:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: "" 
