apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/managed-by: argocd
    argocd.argoproj.io/enable-namespace-creation: "true"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.1.5
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: fullnameOverride
          value: my-postgres
    path: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

