apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  source:
    path: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.5.1
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
