apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jfrog.io
    chart: artifactory
    targetRevision: 107.59.9  # You can also use "latest" if desired
    helm:
      valueFiles:
        - apps/jfrog/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jfrog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
