apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jfrog.io
    chart: artifactory
    targetRevision: 107.59.9
    helm:
      values: |
        postgresql:
          enabled: false

        database:
          type: postgresql
          driver: org.postgresql.Driver
          secrets:
            user:
              name: jfrog-secret
              key: db-user
            password:
              name: jfrog-secret
              key: db-password
            url:
              name: jfrog-secret
              key: db-url

        artifactory:
          persistence:
            enabled: true
            size: 5Gi
            storageClass: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: jfrog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
